name: github-action
on: [push, pull_request]

jobs:
  super-lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    env:
      OS: ${{ matrix.os }}
      python: '3.7'

    steps:
      - name: Initialize Action
        run: python .github/workflow/commit_data.py

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          DEFAULT-BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_PYTHON_BLACK: true

